version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g aws-cdk
      - npm ci
      - cdk acknowledge 34635
  build:
    commands:
      - npm run build
      - cdk deploy AwsCloudPlatformStack --require-approval never
  post_build:
    commands:
      - echo "Build completed"
